/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __markAsModule = (target) => __defProp(target, "__esModule", { value: true });
var __export = (target, all) => {
  __markAsModule(target);
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __reExport = (target, module2, desc) => {
  if (module2 && typeof module2 === "object" || typeof module2 === "function") {
    for (let key of __getOwnPropNames(module2))
      if (!__hasOwnProp.call(target, key) && key !== "default")
        __defProp(target, key, { get: () => module2[key], enumerable: !(desc = __getOwnPropDesc(module2, key)) || desc.enumerable });
  }
  return target;
};
var __toModule = (module2) => {
  return __reExport(__markAsModule(__defProp(module2 != null ? __create(__getProtoOf(module2)) : {}, "default", module2 && module2.__esModule && "default" in module2 ? { get: () => module2.default, enumerable: true } : { value: module2, enumerable: true })), module2);
};

// main.ts
__export(exports, {
  default: () => NotePublisherPlugin
});
var import_obsidian = __toModule(require("obsidian"));
var path = __toModule(require("path"));
var DEFAULT_SETTINGS = {
  mcpServerUrl: "http://127.0.0.1:3000",
  headlessMode: true,
  openEditorAfterPublish: true,
  showNotification: true,
  defaultTags: [],
  useApiMode: true,
  conversionMode: "plugin"
};
async function updateFrontmatter(app, file, updates) {
  const content = await app.vault.read(file);
  const frontmatterRegex = /^---\s*\n([\s\S]*?)\n---\s*\n?/;
  const match = content.match(frontmatterRegex);
  let newContent;
  if (match) {
    const frontmatterStr = match[1];
    const frontmatterLines = frontmatterStr.split("\n");
    const frontmatterObj = {};
    for (const line of frontmatterLines) {
      const colonIndex = line.indexOf(":");
      if (colonIndex > 0) {
        const key = line.substring(0, colonIndex).trim();
        let value = line.substring(colonIndex + 1).trim();
        if (value.startsWith('"') && value.endsWith('"') || value.startsWith("'") && value.endsWith("'")) {
          value = value.slice(1, -1);
        }
        frontmatterObj[key] = value;
      }
    }
    for (const [key, value] of Object.entries(updates)) {
      if (value === null || value === void 0) {
        delete frontmatterObj[key];
      } else {
        frontmatterObj[key] = value;
      }
    }
    const newFrontmatterLines = [];
    for (const [key, value] of Object.entries(frontmatterObj)) {
      if (value === "" || value === null || value === void 0) {
        newFrontmatterLines.push(`${key}: ""`);
      } else if (typeof value === "string" && (value.includes(":") || value.includes("#") || value.includes('"'))) {
        newFrontmatterLines.push(`${key}: "${value.replace(/"/g, '\\"')}"`);
      } else {
        newFrontmatterLines.push(`${key}: ${value}`);
      }
    }
    const newFrontmatter = `---
${newFrontmatterLines.join("\n")}
---
`;
    newContent = content.replace(frontmatterRegex, newFrontmatter);
  } else {
    const newFrontmatterLines = [];
    for (const [key, value] of Object.entries(updates)) {
      if (value !== null && value !== void 0) {
        if (value === "") {
          newFrontmatterLines.push(`${key}: ""`);
        } else if (typeof value === "string" && (value.includes(":") || value.includes("#") || value.includes('"'))) {
          newFrontmatterLines.push(`${key}: "${value.replace(/"/g, '\\"')}"`);
        } else {
          newFrontmatterLines.push(`${key}: ${value}`);
        }
      }
    }
    const newFrontmatter = `---
${newFrontmatterLines.join("\n")}
---

`;
    newContent = newFrontmatter + content;
  }
  await app.vault.modify(file, newContent);
}
function getTodayDate() {
  const now = new Date();
  const year = now.getFullYear();
  const month = String(now.getMonth() + 1).padStart(2, "0");
  const day = String(now.getDate()).padStart(2, "0");
  return `${year}-${month}-${day}`;
}
function getPublishDateFromCache(cache) {
  var _a;
  return (_a = cache == null ? void 0 : cache.frontmatter) == null ? void 0 : _a.publish_date;
}
var MCPClient = class {
  constructor(serverUrl) {
    this.requestId = 0;
    this.serverUrl = serverUrl.replace(/\/$/, "");
  }
  setServerUrl(url) {
    this.serverUrl = url.replace(/\/$/, "");
  }
  async healthCheck() {
    try {
      const response = await (0, import_obsidian.requestUrl)({
        url: `${this.serverUrl}/health`,
        method: "GET"
      });
      return response.status === 200;
    } catch (e) {
      return false;
    }
  }
  async callTool(toolName, args) {
    var _a, _b, _c;
    this.requestId++;
    const requestBody = {
      jsonrpc: "2.0",
      id: this.requestId,
      method: "tools/call",
      params: {
        name: toolName,
        arguments: args
      }
    };
    const bodyStr = JSON.stringify(requestBody);
    console.log(`[Note Publisher] Calling tool: ${toolName}`);
    console.log(`[Note Publisher] URL: ${this.serverUrl}/mcp`);
    console.log(`[Note Publisher] Body size: ${bodyStr.length} bytes`);
    try {
      const response = await (0, import_obsidian.requestUrl)({
        url: `${this.serverUrl}/mcp`,
        method: "POST",
        headers: {
          "Content-Type": "application/json"
        },
        body: bodyStr,
        throw: false
      });
      console.log(`[Note Publisher] Response status: ${response.status}`);
      console.log(`[Note Publisher] Response text: ${response.text.substring(0, 300)}`);
      if (response.status !== 200) {
        throw new Error(`HTTP error: ${response.status} - ${response.text}`);
      }
      const mcpResponse = JSON.parse(response.text);
      if (mcpResponse.error) {
        throw new Error(mcpResponse.error.message);
      }
      if ((_c = (_b = (_a = mcpResponse.result) == null ? void 0 : _a.content) == null ? void 0 : _b[0]) == null ? void 0 : _c.text) {
        return JSON.parse(mcpResponse.result.content[0].text);
      }
      return mcpResponse.result;
    } catch (e) {
      console.error(`[Note Publisher] Request failed:`, e);
      throw e;
    }
  }
  async publishWithImages(params) {
    var _a;
    try {
      console.log(`[Note Publisher] Using post-draft-note-with-images (API mode)`);
      const toolArgs = {
        title: params.title,
        body: params.markdown,
        bodyFormat: params.bodyFormat || "markdown",
        tags: params.tags || []
      };
      if (params.images && params.images.length > 0) {
        toolArgs.images = params.images;
        console.log(`[Note Publisher] Images: ${params.images.length}`);
      }
      if (params.eyecatch && params.eyecatch.base64) {
        toolArgs.eyecatch = params.eyecatch;
        console.log(`[Note Publisher] Eyecatch: ${params.eyecatch.fileName}`);
      }
      const result = await this.callTool("post-draft-note-with-images", toolArgs);
      if (result.success || result.noteId) {
        return {
          success: true,
          message: "\u4E0B\u66F8\u304D\u3092\u4F5C\u6210\u3057\u307E\u3057\u305F",
          title: params.title,
          noteUrl: result.editUrl || result.noteUrl,
          imageCount: result.imageCount || 0,
          images: ((_a = result.uploadedImages) == null ? void 0 : _a.map((i) => i.name)) || [],
          tags: params.tags || []
        };
      } else {
        return {
          success: false,
          error: result.error || result.message || "Unknown error"
        };
      }
    } catch (error) {
      return {
        success: false,
        error: error.message || "Unknown error"
      };
    }
  }
  async publishFromObsidianRemote(params) {
    const hasEyecatch = params.eyecatch && params.eyecatch.base64;
    try {
      console.log(`[Note Publisher] Using post-draft-note (eyecatch: ${hasEyecatch ? "yes" : "no"})`);
      const toolArgs = {
        title: params.title,
        body: params.markdown,
        bodyFormat: params.bodyFormat || "markdown",
        tags: params.tags
      };
      if (hasEyecatch) {
        toolArgs.eyecatch = params.eyecatch;
      }
      const result = await this.callTool("post-draft-note", toolArgs);
      if (result.success || result.noteId) {
        return {
          success: true,
          message: "\u4E0B\u66F8\u304D\u3092\u4F5C\u6210\u3057\u307E\u3057\u305F",
          title: params.title,
          noteUrl: result.editUrl || result.noteUrl,
          imageCount: hasEyecatch ? 1 : 0,
          images: hasEyecatch ? [params.eyecatch.fileName] : [],
          tags: params.tags || []
        };
      } else {
        return {
          success: false,
          error: result.error || result.message || "Unknown error"
        };
      }
    } catch (error) {
      return {
        success: false,
        error: error.message || "Unknown error"
      };
    }
  }
};
async function parseMarkdownFile(app, file, conversionMode) {
  var _a;
  const content = await app.vault.read(file);
  const cache = app.metadataCache.getFileCache(file);
  const title = extractTitle(content, file, cache);
  const tags = extractTags(cache);
  const fileDir = ((_a = file.parent) == null ? void 0 : _a.path) || "";
  const eyecatch = await extractEyecatch(app, cache, fileDir);
  const body = prepareBody(content, conversionMode);
  const images = await extractImages(app, content, file);
  return {
    title,
    body,
    tags,
    images,
    eyecatch
  };
}
function extractTitle(content, file, cache) {
  const frontmatter = cache == null ? void 0 : cache.frontmatter;
  if (frontmatter == null ? void 0 : frontmatter.title) {
    return String(frontmatter.title);
  }
  const h1Match = content.match(/^#\s+(.+)$/m);
  if (h1Match) {
    return h1Match[1].trim();
  }
  return file.basename;
}
function extractTags(cache) {
  const frontmatter = cache == null ? void 0 : cache.frontmatter;
  if (!(frontmatter == null ? void 0 : frontmatter.tags))
    return [];
  if (Array.isArray(frontmatter.tags)) {
    return frontmatter.tags.map((t) => String(t).replace(/^#/, ""));
  }
  if (typeof frontmatter.tags === "string") {
    return frontmatter.tags.split(",").map((t) => t.trim().replace(/^#/, ""));
  }
  return [];
}
async function extractEyecatch(app, cache, fileDir) {
  const frontmatter = cache == null ? void 0 : cache.frontmatter;
  if (!(frontmatter == null ? void 0 : frontmatter.eyecatch))
    return void 0;
  const eyecatchPath = String(frontmatter.eyecatch);
  console.log(`[Note Publisher] Eyecatch path from frontmatter: ${eyecatchPath}`);
  const imageInfo = await resolveAndEncodeImage(app, eyecatchPath, fileDir);
  if (imageInfo && imageInfo.exists) {
    console.log(`[Note Publisher] Eyecatch image found: ${imageInfo.localPath}`);
    return imageInfo;
  } else {
    console.log(`[Note Publisher] Eyecatch image NOT found: ${eyecatchPath}`);
    return void 0;
  }
}
function generateUUID() {
  return "xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g, (c) => {
    const r = Math.random() * 16 | 0;
    const v = c === "x" ? r : r & 3 | 8;
    return v.toString(16);
  });
}
function escapeHtml(text) {
  return text.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;").replace(/'/g, "&#039;");
}
function addUUIDAttributes(html) {
  return html.replace(/<(\w+)([^>]*)>/g, (match, tag, attrs) => {
    if (tag === "hr" || tag === "br" || tag === "img" || attrs.includes("/")) {
      return match;
    }
    const uuid = generateUUID();
    return `<${tag}${attrs} name="${uuid}" id="${uuid}">`;
  });
}
function processInline(text) {
  let result = text;
  result = result.replace(/==(.+?)==/g, "<strong>$1</strong>");
  result = result.replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>");
  result = result.replace(/\*([^*\n]+)\*/g, "<em>$1</em>");
  result = result.replace(/~~(.+?)~~/g, "<del>$1</del>");
  result = result.replace(/\[([^\]]+)\]\(([^)]+)\)/g, '<a href="$2">$1</a>');
  result = result.replace(/\[\[([^\]|]+)\|([^\]]+)\]\]/g, "$2");
  result = result.replace(/\[\[([^\]]+)\]\]/g, "$1");
  return result;
}
function isSpecialLine(line) {
  const trimmed = line.trim();
  if (!trimmed)
    return false;
  if (/^#{1,6}\s+/.test(trimmed))
    return true;
  if (/^[-*]\s+/.test(trimmed))
    return true;
  if (/^\d+\.\s+/.test(trimmed))
    return true;
  if (/^>/.test(trimmed))
    return true;
  if (/^-{3,}$/.test(trimmed) || /^\*{3,}$/.test(trimmed))
    return true;
  if (/^__(?:CODE_BLOCK|IMAGE)_\d+__$/.test(trimmed))
    return true;
  return false;
}
function convertMarkdownToNoteHtml(markdown) {
  if (!markdown)
    return "";
  let text = markdown.replace(/\r\n/g, "\n").replace(/\r/g, "\n");
  const codeBlocks = [];
  text = text.replace(/```(\w*)\n?([\s\S]*?)```/g, (_match, _lang, code) => {
    const index = codeBlocks.length;
    codeBlocks.push(`<pre><code>${escapeHtml(code.trim())}</code></pre>`);
    return `__CODE_BLOCK_${index}__`;
  });
  const inlineCodes = [];
  text = text.replace(/`([^`\n]+)`/g, (_match, code) => {
    const index = inlineCodes.length;
    inlineCodes.push(`<code>${escapeHtml(code)}</code>`);
    return `__INLINE_CODE_${index}__`;
  });
  const imageRefs = [];
  const stashImage = (match) => {
    const index = imageRefs.length;
    imageRefs.push(match);
    return `__IMAGE_${index}__`;
  };
  text = text.replace(/!\[\[[^\]]+\]\]/g, stashImage);
  text = text.replace(/!\[[^\]]*\]\([^)]+\)/g, stashImage);
  text = text.replace(/\*\*((?:(?!\n\n)(?!\*\*)[\s\S])+?)\*\*/g, "<strong>$1</strong>");
  const result = [];
  for (const paragraph of text.split(/\n\n+/)) {
    const trimmedPara = paragraph.trim();
    if (!trimmedPara)
      continue;
    const lines = trimmedPara.split("\n");
    if (!lines.some(isSpecialLine)) {
      const processed = lines.map((l) => processInline(l.trim())).filter((l) => l);
      if (processed.length > 0) {
        result.push(`<p>${processed.join("<br>")}</p>`);
      }
      continue;
    }
    const state = {
      list: null,
      items: [],
      quote: []
    };
    const closeList = () => {
      if (state.list && state.items.length > 0) {
        const tag = state.list;
        result.push(`<${tag}>${state.items.map((i) => `<li>${i}</li>`).join("")}</${tag}>`);
      }
      state.list = null;
      state.items = [];
    };
    const closeQuote = () => {
      if (state.quote.length > 0) {
        result.push(`<blockquote>${state.quote.join("<br>")}</blockquote>`);
        state.quote = [];
      }
    };
    const closeAll = () => {
      closeList();
      closeQuote();
    };
    for (const line of lines) {
      const trimmedLine = line.trim();
      if (!trimmedLine)
        continue;
      if (/^__CODE_BLOCK_\d+__$/.test(trimmedLine)) {
        closeAll();
        const index = parseInt(trimmedLine.replace(/\D+/g, ""), 10);
        result.push(codeBlocks[index]);
        continue;
      }
      if (/^__IMAGE_\d+__$/.test(trimmedLine)) {
        closeAll();
        result.push(trimmedLine);
        continue;
      }
      const headingMatch = trimmedLine.match(/^(#{1,6})\s+(.+)$/);
      if (headingMatch) {
        closeAll();
        const level = headingMatch[1].length;
        const content = processInline(headingMatch[2]);
        if (level <= 2) {
          result.push(`<h2>${content}</h2>`);
        } else if (level === 3) {
          result.push(`<h3>${content}</h3>`);
        } else {
          result.push(`<p><strong>${content}</strong></p>`);
        }
        continue;
      }
      if (/^-{3,}$/.test(trimmedLine) || /^\*{3,}$/.test(trimmedLine)) {
        closeAll();
        result.push("<hr>");
        continue;
      }
      const quoteMatch = trimmedLine.match(/^>\s?(.*)$/);
      if (quoteMatch) {
        closeList();
        state.quote.push(processInline(quoteMatch[1]));
        continue;
      }
      closeQuote();
      const ulMatch = trimmedLine.match(/^[-*]\s+(.+)$/);
      if (ulMatch) {
        if (state.list === "ol")
          closeList();
        state.list = "ul";
        state.items.push(processInline(ulMatch[1]));
        continue;
      }
      const olMatch = trimmedLine.match(/^\d+\.\s+(.+)$/);
      if (olMatch) {
        if (state.list === "ul")
          closeList();
        state.list = "ol";
        state.items.push(processInline(olMatch[1]));
        continue;
      }
      closeList();
      result.push(`<p>${processInline(trimmedLine)}</p>`);
    }
    closeAll();
  }
  const merged = [];
  for (const item of result) {
    const prev = merged[merged.length - 1];
    if (prev && prev.startsWith("<blockquote>") && prev.endsWith("</blockquote>") && item.startsWith("<blockquote>") && item.endsWith("</blockquote>")) {
      const prevContent = prev.slice("<blockquote>".length, -"</blockquote>".length);
      const curContent = item.slice("<blockquote>".length, -"</blockquote>".length);
      merged[merged.length - 1] = `<blockquote>${prevContent}<br>${curContent}</blockquote>`;
    } else {
      merged.push(item);
    }
  }
  let html = merged.join("");
  inlineCodes.forEach((code, index) => {
    html = html.split(`__INLINE_CODE_${index}__`).join(code);
  });
  codeBlocks.forEach((code, index) => {
    html = html.split(`__CODE_BLOCK_${index}__`).join(code);
  });
  html = addUUIDAttributes(html);
  imageRefs.forEach((ref, index) => {
    html = html.split(`__IMAGE_${index}__`).join(ref);
  });
  return html.trim();
}
function prepareBody(content, conversionMode) {
  let body = content;
  body = body.replace(/^---\s*\n[\s\S]*?\n---\s*\n?/, "");
  body = body.replace(/^#\s+.+\n*/, "");
  body = body.trim();
  if (conversionMode === "server") {
    return body;
  }
  return convertMarkdownToNoteHtml(body);
}
async function extractImages(app, content, file) {
  var _a;
  const images = [];
  const fileDir = ((_a = file.parent) == null ? void 0 : _a.path) || "";
  const obsidianRegex = /!\[\[([^\]|]+)(?:\|[^\]]+)?\]\]/g;
  let match;
  while ((match = obsidianRegex.exec(content)) !== null) {
    const fileName = match[1].trim();
    const imageInfo = await resolveAndEncodeImage(app, fileName, fileDir);
    if (imageInfo) {
      images.push(imageInfo);
    }
  }
  const mdRegex = /!\[([^\]]*)\]\(([^)]+)\)/g;
  while ((match = mdRegex.exec(content)) !== null) {
    const srcPath = match[2].trim();
    if (srcPath.startsWith("http://") || srcPath.startsWith("https://")) {
      continue;
    }
    const imageInfo = await resolveAndEncodeImage(app, srcPath, fileDir);
    if (imageInfo) {
      images.push(imageInfo);
    }
  }
  return images;
}
async function resolveAndEncodeImage(app, imagePath, baseDir) {
  const fileName = path.basename(imagePath);
  const imageFile = resolveImageFile(app, imagePath, baseDir);
  if (!imageFile) {
    return {
      fileName,
      localPath: imagePath,
      exists: false
    };
  }
  try {
    const arrayBuffer = await app.vault.readBinary(imageFile);
    const base64 = arrayBufferToBase64(arrayBuffer);
    const mimeType = getMimeType(imageFile.extension);
    return {
      fileName,
      localPath: imageFile.path,
      exists: true,
      base64,
      mimeType
    };
  } catch (e) {
    console.error(`Failed to read image: ${imagePath}`, e);
    return {
      fileName,
      localPath: imagePath,
      exists: false
    };
  }
}
function resolveImageFile(app, imagePath, baseDir) {
  const vault = app.vault;
  const linkedFile = app.metadataCache.getFirstLinkpathDest(imagePath, baseDir);
  if (linkedFile && linkedFile instanceof import_obsidian.TFile) {
    return linkedFile;
  }
  const directFile = vault.getAbstractFileByPath(imagePath);
  if (directFile && directFile instanceof import_obsidian.TFile) {
    return directFile;
  }
  const relativePath = baseDir ? `${baseDir}/${imagePath}` : imagePath;
  const relativeFile = vault.getAbstractFileByPath(relativePath);
  if (relativeFile && relativeFile instanceof import_obsidian.TFile) {
    return relativeFile;
  }
  const commonDirs = ["images", "attachments", "assets", "media", ""];
  const baseName = path.basename(imagePath);
  for (const dir of commonDirs) {
    const tryPath = dir ? `${baseDir}/${dir}/${baseName}` : `${baseDir}/${baseName}`;
    const tryFile = vault.getAbstractFileByPath(tryPath);
    if (tryFile && tryFile instanceof import_obsidian.TFile) {
      return tryFile;
    }
    const rootPath = dir ? `${dir}/${baseName}` : baseName;
    const rootFile = vault.getAbstractFileByPath(rootPath);
    if (rootFile && rootFile instanceof import_obsidian.TFile) {
      return rootFile;
    }
  }
  return null;
}
function arrayBufferToBase64(buffer) {
  const bytes = new Uint8Array(buffer);
  let binary = "";
  for (let i = 0; i < bytes.byteLength; i++) {
    binary += String.fromCharCode(bytes[i]);
  }
  return btoa(binary);
}
function getMimeType(extension) {
  const mimeTypes = {
    "png": "image/png",
    "jpg": "image/jpeg",
    "jpeg": "image/jpeg",
    "gif": "image/gif",
    "webp": "image/webp",
    "svg": "image/svg+xml",
    "bmp": "image/bmp"
  };
  return mimeTypes[extension.toLowerCase()] || "image/png";
}
var PublishConfirmModal = class extends import_obsidian.Modal {
  constructor(app, parsedMarkdown, onConfirm, onCancel) {
    super(app);
    this.parsedMarkdown = parsedMarkdown;
    this.onConfirm = onConfirm;
    this.onCancel = onCancel;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.addClass("note-publisher-modal");
    contentEl.createEl("h2", { text: "Publish to note.com" });
    new import_obsidian.Setting(contentEl).setName("Title").setDesc(this.parsedMarkdown.title);
    if (this.parsedMarkdown.tags.length > 0) {
      new import_obsidian.Setting(contentEl).setName("Tags").setDesc(this.parsedMarkdown.tags.join(", "));
    }
    const eyecatch = this.parsedMarkdown.eyecatch;
    if (eyecatch) {
      new import_obsidian.Setting(contentEl).setName("Eyecatch").setDesc(eyecatch.exists ? `\u2713 ${eyecatch.fileName}` : `\u2717 ${eyecatch.fileName} (not found)`);
    } else {
      new import_obsidian.Setting(contentEl).setName("Eyecatch").setDesc("None (no eyecatch in frontmatter)");
    }
    const images = this.parsedMarkdown.images;
    if (images.length > 0) {
      const imageSection = contentEl.createDiv("image-section");
      imageSection.createEl("h3", { text: `Images (${images.length})` });
      const imageList = imageSection.createDiv("image-list");
      const foundImages = images.filter((i) => i.exists);
      const missingImages = images.filter((i) => !i.exists);
      foundImages.forEach((img) => {
        const item = imageList.createDiv("image-item found");
        item.setText(`\u2713 ${img.fileName}`);
      });
      missingImages.forEach((img) => {
        const item = imageList.createDiv("image-item missing");
        item.setText(`\u2717 ${img.fileName} (not found)`);
      });
      if (missingImages.length > 0) {
        imageSection.createEl("p", {
          text: `Warning: ${missingImages.length} image(s) not found and will be skipped.`,
          cls: "mod-warning"
        });
      }
    }
    const plainBody = this.parsedMarkdown.body.replace(/<\/(p|h[1-6]|li|blockquote|pre)>/g, " ").replace(/<br\s*\/?>/g, " ").replace(/<[^>]+>/g, "").replace(/\s+/g, " ").trim();
    const bodyPreview = plainBody.substring(0, 200);
    new import_obsidian.Setting(contentEl).setName("Body Preview").setDesc(bodyPreview + (plainBody.length > 200 ? "..." : ""));
    const buttonContainer = contentEl.createDiv("button-container");
    const cancelBtn = buttonContainer.createEl("button", { text: "Cancel" });
    cancelBtn.addEventListener("click", () => {
      this.close();
      this.onCancel();
    });
    const confirmBtn = buttonContainer.createEl("button", {
      text: "Publish as Draft",
      cls: "mod-cta"
    });
    confirmBtn.addEventListener("click", () => {
      this.close();
      this.onConfirm();
    });
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
var NotePublisherSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Note Publisher Settings (v1.2.15)" });
    new import_obsidian.Setting(containerEl).setName("MCP Server URL").setDesc("noteMCP\u30B5\u30FC\u30D0\u30FC\u306EURL\uFF08\u4F8B: http://127.0.0.1:3000\uFF09\u3002localhost\u3067\u306F\u306A\u304FIP\u30A2\u30C9\u30EC\u30B9\u3092\u6307\u5B9A\u3057\u3066\u304F\u3060\u3055\u3044").addText((text) => text.setPlaceholder(DEFAULT_SETTINGS.mcpServerUrl).setValue(this.plugin.settings.mcpServerUrl).onChange(async (value) => {
      this.plugin.settings.mcpServerUrl = value || DEFAULT_SETTINGS.mcpServerUrl;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Markdown\u5909\u63DB (v1.2.15)").setDesc("\u3053\u306E\u30D7\u30E9\u30B0\u30A4\u30F3\u3067\u5909\u63DB = \u592A\u5B57\u30FB\u898B\u51FA\u3057\u30FB\u7B87\u6761\u66F8\u304D\u30FB\u30B3\u30FC\u30C9\u30D6\u30ED\u30C3\u30AF\u3092HTML\u306B\u5909\u63DB\u3057\u3066\u304B\u3089\u9001\u4FE1\u3057\u307E\u3059\uFF08\u63A8\u5968\uFF09\u3002noteMCP\u30B5\u30FC\u30D0\u30FC\u306B\u4EFB\u305B\u308B = Markdown\u306E\u307E\u307E\u9001\u4FE1\u3057\u307E\u3059\uFF08\u30B5\u30FC\u30D0\u30FC\u304CMarkdown\u5909\u63DB\u306B\u5BFE\u5FDC\u3057\u3066\u3044\u306A\u3044\u5834\u5408\u3001\u66F8\u5F0F\u304C\u53CD\u6620\u3055\u308C\u307E\u305B\u3093\uFF09\u3002").addDropdown((dropdown) => dropdown.addOption("plugin", "\u3053\u306E\u30D7\u30E9\u30B0\u30A4\u30F3\u3067\u5909\u63DB\uFF08\u63A8\u5968\uFF09").addOption("server", "noteMCP\u30B5\u30FC\u30D0\u30FC\u306B\u4EFB\u305B\u308B").setValue(this.plugin.settings.conversionMode).onChange(async (value) => {
      this.plugin.settings.conversionMode = value === "server" ? "server" : "plugin";
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("API Mode (v1.2.0)").setDesc("API\u7D4C\u7531\u3067\u753B\u50CF\u3092\u672C\u6587\u306B\u633F\u5165\uFF08\u63A8\u5968: ON - \u5B89\u5B9A\u30FB\u9AD8\u901F\uFF09").addToggle((toggle) => toggle.setValue(this.plugin.settings.useApiMode).onChange(async (value) => {
      this.plugin.settings.useApiMode = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Headless Mode").setDesc("\u30B5\u30FC\u30D0\u30FC\u5074\u3067\u30D6\u30E9\u30A6\u30B6\u3092\u975E\u8868\u793A\u3067\u5B9F\u884C\uFF08\u63A8\u5968: ON\uFF09").addToggle((toggle) => toggle.setValue(this.plugin.settings.headlessMode).onChange(async (value) => {
      this.plugin.settings.headlessMode = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Open Editor After Publish").setDesc("\u4E0B\u66F8\u304D\u4F5C\u6210\u5F8C\u306Bnote.com\u306E\u30A8\u30C7\u30A3\u30BF\u30FC\u3092\u30D6\u30E9\u30A6\u30B6\u3067\u958B\u304F").addToggle((toggle) => toggle.setValue(this.plugin.settings.openEditorAfterPublish).onChange(async (value) => {
      this.plugin.settings.openEditorAfterPublish = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Show Notification").setDesc("\u6210\u529F/\u30A8\u30E9\u30FC\u6642\u306B\u901A\u77E5\u3092\u8868\u793A").addToggle((toggle) => toggle.setValue(this.plugin.settings.showNotification).onChange(async (value) => {
      this.plugin.settings.showNotification = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Default Tags").setDesc("\u6BCE\u56DE\u81EA\u52D5\u7684\u306B\u8FFD\u52A0\u3059\u308B\u30BF\u30B0\uFF08\u30AB\u30F3\u30DE\u533A\u5207\u308A\uFF09").addText((text) => text.setPlaceholder("tag1, tag2, tag3").setValue(this.plugin.settings.defaultTags.join(", ")).onChange(async (value) => {
      this.plugin.settings.defaultTags = value.split(",").map((t) => t.trim()).filter((t) => t.length > 0);
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Test Connection").setDesc("MCP\u30B5\u30FC\u30D0\u30FC\u3068\u306E\u63A5\u7D9A\u3092\u30C6\u30B9\u30C8").addButton((button) => button.setButtonText("Test").onClick(async () => {
      button.setButtonText("Testing...");
      button.setDisabled(true);
      try {
        const response = await fetch(`${this.plugin.settings.mcpServerUrl}/health`);
        if (response.ok) {
          button.setButtonText("Success!");
          setTimeout(() => {
            button.setButtonText("Test");
            button.setDisabled(false);
          }, 2e3);
        } else {
          throw new Error(`HTTP ${response.status}`);
        }
      } catch (e) {
        button.setButtonText("Failed");
        setTimeout(() => {
          button.setButtonText("Test");
          button.setDisabled(false);
        }, 2e3);
      }
    }));
  }
};
var NotePublisherPlugin = class extends import_obsidian.Plugin {
  async onload() {
    await this.loadSettings();
    this.mcpClient = new MCPClient(this.settings.mcpServerUrl);
    this.addCommand({
      id: "publish-to-note",
      name: "Publish to note.com",
      checkCallback: (checking) => {
        const file = this.app.workspace.getActiveFile();
        if (file && file.extension === "md") {
          if (!checking) {
            this.publishCurrentFile(file);
          }
          return true;
        }
        return false;
      }
    });
    this.addCommand({
      id: "publish-to-note-quick",
      name: "Publish to note.com (Quick - no confirmation)",
      checkCallback: (checking) => {
        const file = this.app.workspace.getActiveFile();
        if (file && file.extension === "md") {
          if (!checking) {
            this.publishCurrentFile(file, true);
          }
          return true;
        }
        return false;
      }
    });
    this.addRibbonIcon("upload", "Publish to note.com", async () => {
      const file = this.app.workspace.getActiveFile();
      if (file && file.extension === "md") {
        await this.publishCurrentFile(file);
      } else {
        new import_obsidian.Notice("Please open a Markdown file to publish");
      }
    });
    this.addSettingTab(new NotePublisherSettingTab(this.app, this));
    console.log("Note Publisher plugin loaded (v1.2.2)");
  }
  onunload() {
    console.log("Note Publisher plugin unloaded");
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    var _a;
    await this.saveData(this.settings);
    (_a = this.mcpClient) == null ? void 0 : _a.setServerUrl(this.settings.mcpServerUrl);
  }
  async publishCurrentFile(file, skipConfirmation = false) {
    try {
      const parsedMarkdown = await parseMarkdownFile(this.app, file, this.settings.conversionMode);
      if (skipConfirmation) {
        await this.doPublish(parsedMarkdown, file);
      } else {
        new PublishConfirmModal(this.app, parsedMarkdown, () => this.doPublish(parsedMarkdown, file), () => {
        }).open();
      }
    } catch (error) {
      this.handleError(error);
    }
  }
  async doPublish(parsedMarkdown, file) {
    const loadingNotice = new import_obsidian.Notice("Publishing to note.com...", 0);
    try {
      await updateFrontmatter(this.app, file, {
        status: "publishing",
        publish_error: ""
      });
      console.log("[Note Publisher] Status changed to: publishing");
    } catch (e) {
      console.error("[Note Publisher] Failed to update frontmatter to publishing:", e);
    }
    try {
      const allTags = [...parsedMarkdown.tags, ...this.settings.defaultTags];
      const uniqueTags = [...new Set(allTags)].slice(0, 10);
      const bodyFormat = this.settings.conversionMode === "plugin" ? "html" : "markdown";
      console.log(`[Note Publisher] Conversion mode: ${this.settings.conversionMode} (bodyFormat=${bodyFormat})`);
      let result;
      if (this.settings.useApiMode) {
        const validImages = parsedMarkdown.images.filter((i) => i.exists && i.base64);
        const imageData = validImages.map((img) => ({
          fileName: img.fileName,
          base64: img.base64,
          mimeType: img.mimeType
        }));
        let eyecatchData;
        if (parsedMarkdown.eyecatch && parsedMarkdown.eyecatch.exists && parsedMarkdown.eyecatch.base64) {
          eyecatchData = {
            fileName: parsedMarkdown.eyecatch.fileName,
            base64: parsedMarkdown.eyecatch.base64,
            mimeType: parsedMarkdown.eyecatch.mimeType
          };
        }
        result = await this.mcpClient.publishWithImages({
          title: parsedMarkdown.title,
          markdown: parsedMarkdown.body,
          tags: uniqueTags,
          images: imageData,
          eyecatch: eyecatchData,
          bodyFormat
        });
      } else {
        const requestBody = {
          title: parsedMarkdown.title,
          markdown: parsedMarkdown.body,
          tags: uniqueTags,
          headless: this.settings.headlessMode,
          saveAsDraft: true,
          bodyFormat
        };
        if (parsedMarkdown.eyecatch && parsedMarkdown.eyecatch.exists) {
          requestBody.eyecatch = {
            fileName: parsedMarkdown.eyecatch.fileName,
            base64: parsedMarkdown.eyecatch.base64,
            mimeType: parsedMarkdown.eyecatch.mimeType
          };
        }
        result = await this.mcpClient.publishFromObsidianRemote(requestBody);
      }
      loadingNotice.hide();
      if (result.success) {
        const cache = this.app.metadataCache.getFileCache(file);
        const existingPublishDate = getPublishDateFromCache(cache);
        const successUpdates = {
          status: "published",
          publish_error: ""
        };
        if (result.noteUrl) {
          successUpdates.note_url = result.noteUrl;
        }
        if (!existingPublishDate) {
          successUpdates.publish_date = getTodayDate();
        }
        try {
          await updateFrontmatter(this.app, file, successUpdates);
          console.log("[Note Publisher] Status changed to: published");
        } catch (e) {
          console.error("[Note Publisher] Failed to update frontmatter to published:", e);
        }
        if (this.settings.showNotification) {
          new import_obsidian.Notice(`Draft created: "${result.title}"
${result.imageCount || 0} image(s) inserted`);
        }
        if (this.settings.openEditorAfterPublish) {
          window.open("https://note.com/notes", "_blank");
        }
      } else {
        throw new Error(result.error || "Unknown error");
      }
    } catch (error) {
      loadingNotice.hide();
      const errorMessage = this.getShortErrorMessage(error);
      try {
        await updateFrontmatter(this.app, file, {
          status: "review",
          publish_error: errorMessage
        });
        console.log(`[Note Publisher] Status changed to: review (error: ${errorMessage})`);
      } catch (e) {
        console.error("[Note Publisher] Failed to update frontmatter on error:", e);
      }
      this.handleError(error);
    }
  }
  getShortErrorMessage(error) {
    const message = error.message || String(error);
    if (message.includes("ECONNREFUSED") || message.includes("fetch")) {
      return "MCP\u63A5\u7D9A\u5931\u6557";
    }
    if (message.includes("timeout")) {
      return "\u30BF\u30A4\u30E0\u30A2\u30A6\u30C8";
    }
    if (message.includes("401") || message.includes("\u8A8D\u8A3C")) {
      return "API 401";
    }
    if (message.includes("403")) {
      return "API 403";
    }
    if (message.includes("500")) {
      return "API 500";
    }
    if (message.includes("\u753B\u50CF") || message.includes("image")) {
      return "\u753B\u50CF\u30A2\u30C3\u30D7\u30ED\u30FC\u30C9\u5931\u6557";
    }
    if (message.length > 50) {
      return message.substring(0, 47) + "...";
    }
    return message;
  }
  handleError(error) {
    console.error("Note Publisher error:", error);
    let message = "Failed to publish";
    if (error.message.includes("ECONNREFUSED") || error.message.includes("fetch")) {
      message = `Cannot connect to MCP server at ${this.settings.mcpServerUrl}. Is it running?`;
    } else if (error.message.includes("timeout")) {
      message = "Operation timed out. Please try again.";
    } else if (error.message.includes("\u8A8D\u8A3C")) {
      message = "Authentication failed. Check MCP server credentials.";
    } else {
      message = `Error: ${error.message}`;
    }
    new import_obsidian.Notice(message, 1e4);
  }
};
